# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc15e31dc449d8a43606884aa695955bb664435d214b62268091f86ed7ac54b3f4a7667c40e576e408d755ab72485a540450b945915d5d4e7db7fdcdb00e7ee9

test:
  secret_key_base: 96b208c27a093d0a2a79ec43128cc599d2cdaed6cb6973dc35ed466ec79129bb0ea4348ae3a25b04202603470de54932e62990add830936488c9430bc597785e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
